require "user.options"
require "user.keymaps"
require "user.plugins"
--vimcmd "colorscheme delek"
--vim.cmd "colorscheme darkplus"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.lsp.telescope"
